// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjdrHNEsDRrsfbeJQk7fWJ_0Tw3diiDWE',
    appId: '1:971520545131:web:f483ccef70abce6926fc2e',
    messagingSenderId: '971520545131',
    projectId: 'act13-c71d8',
    authDomain: 'act13-c71d8.firebaseapp.com',
    storageBucket: 'act13-c71d8.firebasestorage.app',
    measurementId: 'G-JE82JHF3EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGH3eGQMfF4RNXVv5BqLPTqoB3X1_vPnc',
    appId: '1:971520545131:android:61059ba904a9490826fc2e',
    messagingSenderId: '971520545131',
    projectId: 'act13-c71d8',
    storageBucket: 'act13-c71d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtxFnbS2792mkxe5y3AWb5Z4zuJ1sgC48',
    appId: '1:971520545131:ios:787c64f400c74d5126fc2e',
    messagingSenderId: '971520545131',
    projectId: 'act13-c71d8',
    storageBucket: 'act13-c71d8.firebasestorage.app',
    iosBundleId: 'com.example.act13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtxFnbS2792mkxe5y3AWb5Z4zuJ1sgC48',
    appId: '1:971520545131:ios:787c64f400c74d5126fc2e',
    messagingSenderId: '971520545131',
    projectId: 'act13-c71d8',
    storageBucket: 'act13-c71d8.firebasestorage.app',
    iosBundleId: 'com.example.act13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjdrHNEsDRrsfbeJQk7fWJ_0Tw3diiDWE',
    appId: '1:971520545131:web:bcf7d192734bad9526fc2e',
    messagingSenderId: '971520545131',
    projectId: 'act13-c71d8',
    authDomain: 'act13-c71d8.firebaseapp.com',
    storageBucket: 'act13-c71d8.firebasestorage.app',
    measurementId: 'G-W8B9089E67',
  );
}
